// quick-keys.ts — the ONE text of the "Scripting quick keys": the export-JSON keys a script needs
// before it walks a screen file. Builders and verifiers kept guessing field names from Figma's Plugin
// API (`characters`, `width`, `visible`, `layout.scroll`) although ir-fields.md had the right ones —
// the reference was never opened by the agent writing the walker. So the same text lives in two
// places, both kept identical by a doc-guard (test/build-screen-docs.test.ts):
//   - the top of claude-plugin/skills/build-screen/references/ir-fields.md, between the
//     `quick-keys:start` / `quick-keys:end` markers;
//   - design/export/SCHEMA.md, which write-out.ts writes next to the data on every pull that writes to
//     disk (CLI + MCP writeToDisk), so a script-writing agent finds it where it looks.
// Edit the text HERE and paste it into ir-fields.md; the guard fails until both agree.

/** File name of the generated copy inside the export dir. Not README.md: in the legacy flat layout the
 *  export dir IS design/, where `dtwin init` writes its own design/README.md. */
export const SCHEMA_DOC_NAME = "SCHEMA.md";

/** First line of the generated copy. A SCHEMA.md without it is the user's file and is never touched. */
export const SCHEMA_MARKER = "<!-- generated by dtwin: scripting quick keys -->";

export const QUICK_KEYS = `## Scripting quick keys

Read these before writing ANY script against an export JSON (field names guessed from Figma's Plugin API are wrong).

- **The tree.** A screen file (\`pages/<Page>/<Screen>__<id>.json\`) holds it in \`nodes[]\` — a \`--node\` pull has exactly
  one root, \`nodes[0]\`; a page-walk layer file holds it at \`tree\`. \`pages/index.json\` \`layers[]\` lists every screen
  — \`file\` and \`texts\` on every row (\`title\` when the frame shows text); a \`--node\`/selection row also has \`w\`/\`h\`
  and, when written, \`variables\`, \`assets\`, \`reference\` (a page-walk row has \`nodes\`/\`bytes\`; its \`reference\` is
  in the layer file) — read it instead of building filenames.
- **Text** is \`text\`, not \`characters\`. Type: \`font.size\`, \`font.lineHeight\`, \`font.weightValue\`, \`font.letterSpacing\`,
  \`font.family\`, \`font.color\` (there is no \`style\`). \`runs[]\` present = mixed formatting: \`font\` is then the FIRST
  run's — read every run.
- **Size** is \`box.w\`/\`box.h\`; there are no top-level \`width\`/\`height\`. A single-screen index row repeats the size
  as \`w\`/\`h\`.
- **Position.** \`box.x\`/\`box.y\` are PAGE (canvas) coordinates — frame-relative = \`box.x − <root>.box.x\` (root = \`nodes[0]\` in a screen file,
  \`tree\` in a page-walk layer file). A node's
  own \`x\`/\`y\` are relative to its nearest frame / component / instance / section ancestor (Figma skips GROUPs and
  boolean operations; the page at top level). Both exist only when the parent does not lay the node out (no auto layout,
  or \`absolute:true\`); inside an auto-layout parent the position comes from the parent's \`layout\` (padding, gap,
  order). \`layout.inferred:true\` is a guess on a frame without auto layout — its children still carry \`x\`/\`y\`.
- **\`absolute:true\`** = out of the parent's auto-layout flow, placed by \`x\`/\`y\`; absent = in flow. \`layout\` describes
  how a node lays out ITS OWN children, so only a node that can hold children has it: \`layout.mode:"absolute"\` =
  no auto layout inside — it never means the node itself is absolute.
- **Child order.** \`children[]\` is Figma's layer list: paint order bottom → top (reversed when the parent's
  \`layout.reverseZ\` is set). In an auto-layout parent it is also the flow order (first = leading); otherwise — and for
  every \`absolute:true\` child — the visual order comes only from \`x\`/\`y\`.
- **Hidden layers stay in the tree.** \`hidden:true\` sits on the layer that was switched off; its descendants are not
  flagged on its account (they may carry their own). Skip a node when it OR ANY ANCESTOR is hidden. There is no
  node-level \`visible\` key.
- **Scroll.** \`clip:true\`; \`scroll\` (\`horizontal\`/\`vertical\`/\`both\`, a node field — not under \`layout\`);
  \`fixedChildren:N\` = the LAST N entries of \`children[]\` stay pinned while the rest scrolls (Figma moves fixed layers
  to the top of the layer list); fixed only — "sticky" is not exposed, so a Sticky child is not marked. Each pinned
  child carries \`x\`/\`y\` (in an auto-layout frame Figma lets only an \`absolute:true\` child be fixed); place it by its
  \`y\` (top bar → sticky top, bottom bar → sticky bottom).
- **Render bounds.** \`renderBox\` (only when it differs from \`box\`) = Figma's render bounds: larger than \`box\` for
  shadow / stroke / blur; on a TEXT usually smaller than \`box\` (observed).
- **Three \`strokes\`.** \`strokes\` is always an object (\`colors[]\`, \`weight\` or \`weights{}\`, \`align\`…);
  \`geometry.strokes\` is a list of SVG path strings; \`tokens.strokes\` is a variable name (or a list).
- **Tokens.** \`tokens.<property>\` = the bound variable's NAME — a string, or a list when several paints are bound;
  paint-level \`fills[].tokens.color\`; text \`textTokens\` / \`runs[].tokens\`. Never map by the hex beside it.
- **Ids.** Inside an instance a node id looks like \`I<instance id>;<layer id>\` (observed) and differs per instance;
  the component itself is \`mainComponent\` (\`key\`/\`setKey\`).
- **Files.** \`asset\` and \`reference\` are paths relative to \`design/export/\` (\`assets/<file>\`); \`assetFrom\` = a hidden
  graphic reusing a visible twin's file; \`assetSkipped\` = no file at all. \`<Screen>.assets.json\`
  (single-screen pulls) lists every file.
- **Older exports.** A file pulled with an older plugin also has \`gridColumnStart:-1\` / \`gridRowStart:-1\` on every node,
  \`gridAlignSelf\` / \`gridJustifySelf\` on a node whose parent is not a grid, and \`layout.mode:"absolute"\` on every
  TEXT, shape, SLICE, STICKY and other leaf type (a node TYPE that cannot hold children has no \`layout\`) — ignore all of it
  (design-diff does).
`;
